---
title: "Running record of the CAMP adol 10-year extension project"
output:
  html_document:
    df_print: paged
    theme: cosmo
    css: tablestyle.css
  pdf_document: default
  word_document: default
---

## Introduction

This document is initiated on October 5, 2018.  Many documents laying out the basic aspects of the project trace back to the initial establishment of the cooperative agreement between the CDC and Emory/UW.  More recent douments are found in a Google Drive folder shared by the team called CAMP E4 - 10 year projection.  This file is meant to represent a running documentation of all decisions we make regarding the tool.

__Basic components:__  

* MSW and WSM only (no MSM, WSW)
* Paper 1 = GC and CT only (no HIV); paper 2 = pregnancy
* Main data structure follows the Excel tool developed over the last two years, but re-written in R for easy compounding over 10 years.
* Main data source = YRBS 10-year trend analysis

### Oct 5, 2018

Insights from email chain commencing 10/2/2018, subject "CAMP 10-year tool extensions":

__Q. Where are the main analyses?__  
A. Some are published in Youth Risk Behavior Survey Data Summary & Trends Report, 2007-2017, available online and in the Google Drive.  More detailed data can be found in 
"2017XXH Trend Report 10 Years.pdf:" and "2017XXH Detail Tables.pdf", both in the YRBS folder of the Google Drive; these are not to be shared.

__Q. Where do we turn for help with these analyses, or for additional analyses?__  
A. DASH's Surveillance Branch (SBSB)

__Q. Can we get mean number of lifetime partners rather than % with 4+ partners?__  
A. Yes, detailed tables should help, or reach out to SBSB.

__Q: Where should be get info on race mixing from?__  
A.  Li Yan suggested an AddHealth analysis by Manhart (2007).  Aral seems less promising (older, convenience sample). Both are in the Google Drive lit folder.

__Q. Should we include groups other than White/Latinx/Black?__  
A. Li Yan says we can if the pops are large enough; if they don't have a strong resaon to, I think we should not add the work.

__Next steps:__  
* Steve will go through YRBS trend reports and two in-house docs in detail and decide on list of questions for SBSB.  This includes keeping an eye on both race and age groups.
* Steve will look at Manhart (2007) and.or think about other options.

### Oct 29, 2018

Beginning to go through reports.

We will need to confirm with SBSB whether they can run numbers for us that are just for FSM/MSF, or will they be for F/M.

We are going to want to confirm up front that we want for MSF/FSM ; Black/Hispanic/White (as defined in survey); for each age 13-18

We are going to want:

Two SPG (or sex)-specific 2-way tables: by year, by age, by race:
  - # of respondents total
  - # of respondents who have ever had sex
  - # of respondents who used a condom at last intercourse

Two sets of SPG/sex-specific matrices:

For each race, for each survey year:
  - Two matrices, each with current age in the rows and age of first intercourse in the columns
        - The first matrix lists the number of respondents with that current age and age of first intercourse
        - The second matrix lists the mean lifetime number of parterns for those respondents with that current age and age of first intercourse
        
I think we will be able to do this second part a bit differently than we did in the 1-year tool by leveraging the multiple waves.  that is, we can subtract the LNOPs for 15 year olds in one survey from that of 17 year olds in the next survey, to determine the average number of new partners over the two years - something like that.

Initiated conversation with Li Yan about getting the data from SBSB.

### Nov 20, 2018

We have determined that we can get all the data we need from the online combined data sets. Elizabeth has been working on that. She has send a single year of data (2007) with all the numbers in a set of five different files.  I am going to work now on the code to import these, and she will continue working on the other years.

I can already see that the numbers are very small (e.g. no 13-year-old Hisp males at all in 2007). So we will most certainly need to do some parametric models rather than full 4-way (sex/age/race/year) stratified numbers.  Indeed, with the age of debut in there, it begins to become 5-way stratified. At this point I am hoping we can do these analyses in R with the numbers that she sends as fully stratified, but we shall see.

I have created a data folder in the project, and placed the files from Elizabeth in them, in a subfolder named 2007_test.

## Nov 25, 2018

Elizebeth has now sent the numbers for all years.  They came as a single .zip file ("yrbs_10yr.zip"), which I have placed in the data folder, and then also extracted in that folder.

### Nov 26, 2018

* Today I wrote the file that does all the data import.
* I also began thinking about how I am going to handle these analyses parametrically:
    + actual pop sizes will need to come from YRBS / census school survey / etc, eeping in mind the time of year issue
    + YRBS gives us weights, not pop sizes per se
    + those weights need to be used in all regressions
    + will probably use multiple linear regression for generating the predicted values of debut /condom use etc.  Tested this on condom use, which is generally linear and behaves well.  Whether % debut does as well is another question.  And whether lifetime partners will is also an issue.

### Nov 27, 2018

Tackling overall school sizes. All taken from American FactFinder:

B14001	SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER
Universe: Population 3 years and over  more information
American Community Survey 1-Year Estimates

All values placed in /data/schoolpops.csv

Code to import them added to CAMP_10yr_import.R

Added code to look at trends in pop sizes by race, sex and age through time (in file exploratory_popsize_trends_by_ethn) to get a sense of what we will need to do with these.  Looked at both absolute numbers and proportions.  Pattern is clear, consistent, and expected: strong evidence that Hisp are increasing over the decade, both as abs and rel.  But then there is relatively little clear pattern in the other two (even though they must add up to 1). For absolute, Blacks are flat; Whites are mostly flat, except older males are declining.

Revisit perhaps with the ages taken out and just look at the total by sex/ethn across years.

## Dec 3, 2018

Deciding to just go with the static pop sizes, averaged across all time periods.  These are currently calculated at the very end of the file "Exploratory_popsize_trends>by_ethn.R".  This still means that we will need a way for people to enter the model in ages 13, 14, 15, leave the model in ages 18 and 19, and some mix of the two for ages 16 (depending on sex and ethn). presumably people should enter negative, and exit with both statuses.

Did some file renaming and reorganization to get things standardized and located in the proper places.

Beginning eversex and then condom use.

## Dec 7, 2018

Realized I need to remove all non-B/H/W kids from the census-derived total pop sizes.  Have sent email to Elizabeth to get these numbers.

Realized I had it set so that F and M were the same pop size; I probably shouldn't do that. Will fix now. Bascially I had been so fixated on popsize by race I just didn't think about sex.

Redid pop sizes so that we have constant compositions by race and sex, and have sex differ by grand mean rather than 50:50.  Just need to hear from Elizabeth to take out the non-BHWs

Worked on eversex and have decided on model5.  It has age as cateogrical, because the pattern across ages is celarly non-linear.  It also - crucially - has an ethn by year interaction, because that was the main point of the 10-year trend.  We may do a run where this interaction is *not* in there, in order to compare results - but for now it's there.

Thta model seems to be working fine for F, but the predicted values for M are doing odd things.  Will return here.  Code is in the masterscript.

## Dec 10, 2018

Elizabeth has sent pop sizes (total weights) for non-BHW. Now integrated.

Debugging eversex_m model - predicted probs don't make sense.

OK, it was an issue with NaNsa - I had told the code to replace Infs with 0s, but not NaNs. Since all of these have weights of 0, it doesn't matter what the value is, but the NaN was causing issues.

Now we face the issue that 13-yo males have higher rates of ever sex than 14-yo males.  This is because the data say so.  Of course the number of them in the data is miniscule, and probably some are over-reporting.

Decision: it's Ok to leave them in.  It's what the data says; plus it doesn't create a logical problem as I feared since we'll need to have a whole slew of 14-year olds enter the model inexperienced, so one can easily have the total % of 14yo who've had sex be less than that of 13yos without having to "unvirginize" anyone.  Plus the effects on the total model output are miniscule.  The alternative -- to return to a parametric form on age -- means getting the shape of the curve in the 15-8 yo range wrong, and that is a much much bigger deal.

## Dec 26, 2018

Since the last record here, I did some more work.

First was to consider a 4-parameter logistic model for sexual debut.  That would allow for a parametric form across age, but not one that requires the value to eventually asymptote at 1, such that we might fit the curve across ages a bit better, and have a more realistic value for 13-year olds.  But it turned out that the two R packages I found for this don't allow for the use ofweights. So I decided this wasn'tworth pursuing any further.

Next was to write all of the code for the back-calculation of mean number of new parters per year.  

Picking up there now.

intrudced y2k as year - 2000, since this makes the parameters far more interpretable here.

Just learned the predict function includes a type argument, which will convert automatically from log odds or log probs to probs.  Went back and changed all code on this.

Did a lot of exploring glm models for nppy.  The age effect is curved; and can't be captured with a cateogrical effect since we have no data for 18 and couldn't extrapolate. But age+age^2 works well, and both terms are significant.  Also, the enth*y2k terms all make sense in terms of my original eyeballing that H rates are falling the fastest.

Hmmm, stuck. Need to have age^2 effect to capture things well.  Then it turns out that age-by-y2k matters, and is signficant, and makes the pattern bettern fitting and perhaps more sensible. But then I was'nt sure if you could have age-by-year and not have age^2-by-year if you have age^2 in the model. So I put in age^2-by-year, and it gets confusing, and then both age-by-year and age^2-by-year become non-significant.  Not sure what to do.

## Dec. 27, 2018

I'm way overthinking this.  No need for age-y2k effect - this is getting way too complicated, far more than they asked for.

Done, with code caried over to master script.

## Jan 4, 2019

Reviewing progress in the new year.
- Have pulled in: pop sizes, eversex, condomuse and mnnppy
- Need to: confirm that pop sizes are done (there are comments in there that I think have been taken care of)
- Need to: pull in diagnoses for first year only (yay) - rest will emerge
- Are there any other multi-dimensional inputs?
- Need to: write the actual function that works with all of these.

Order: confirm pop sizes; think about other needed inputs; make up diagnoses for now so I can work on the function code; work on the function code; think about getting real diagnoses.

Pop sizes confirmed.

Other inputs that may be needed: 
- total age-based pop sizes (not just school)
- diagnoses
- and the little ones about transmission and diagnosis percents and duration that will come form the tool itself

### Jan 7, 2019

Making up diagnoses; pulling in mini-inputs; working on main code.

### Jan 8, 2019

Today I basically wrote the main function.

### Jan 11, 2018

Working on the populations for age 13-18 regardless of school attendance, to be able to convert the diagnoses.

Numbers are readily available for 2010 onwards in AmFactFinder (table PEPALL6N).  But for those years prior to 2010, one must make a special data request:

https://www.census.gov/programs-surveys/popest/data/special-tab/content.html

And of course we are in the middle of a government shutdown:

But really we are most interested in the % of folks who are in school, and that might not have an obvious secular trend to it like total pop nubers do.  So this should be fine - I will calculate the numbers we observe, and look for trends.

Ugh, spent time on it, averaged across years, and found that more than 100% of 15-6 year olds are in HS.  Need to pause and think about something else and then return to this.

### Feb 6, 2019

Returning to think about pop sizes. We want kids in school / all kids, for each cell by sex/age/race. Problem is that some are >100%.

Issue #1: in-school pop sizes are calcualted by averaging across all years 2007-2017.  Then, we use a single average sex ratio across all year, ages, and races to determine sex-specific sizes. Tot pop should use the same method in order to avoid problems.

issues #2: total pop is currently based on 2011-2017, since that is what is available on line.  If we wish the averaging to be the same, we should do a comparable version of in-school pop sizes using just the same years.  This would be really annoying if we have to do it. BUT, I have just written to the Census Burau requesting the numbers, as described at: https://www.census.gov/programs-surveys/popest/data/special-tab/content.html

Ok, I redid the calculations for the totalpops to match the approach infor the school pops (while still not yet having the same set of years). I still get numbes above 100%.  I wonder if this is the same issue we faced earlier, where the age composition of the HS attending population changes over the course of the year. How again did we deal with this in the tool itself? Just looked; it seems that what I'm doing here is comparable to what we do there.  So if the problem persists after I get the final year data, then we may just need to make the assumption that the percent in school is min(1, calculated_value). For these purposes it should not cause a problem.

## Feb 11, 2019
Wrote diag_inschool_calc (yes it's two lines)
Added main fxn output
Ran through code to make sure makes snese (it seems to)
Realize next step is to:
  get real diagnoses numbers
  get real race mixing
  make final decision on coital acts - NO
  run, and be able to show zig-zagging (plus calibrating) to group
  
Spent some hours with the CDC surveillance reports.  Very good news: they publish numbers for sex x age x race.  Downside: huge amounts of missing by race; they don't impute (or at least they did up until 2009).  So we will need to adjust all of them for that. Up next!

## Feb 12, 2019

I will make files that contain: the entire number of diagnoses (Table 1), then the number by sex, then age, then race.  Imputation will follow.

Have entered 2007 at all levels.  Turns out this year was already imputed, so there was no need to do the levels; I think this is only needed from 2010 onwards.

## Feb 13, 2019

Finished exploratory code on initial diagnoses. Model has less zig-zagging for H than my made-up numbers did, but B and W still do. And incidence still declines rapidly for Band H (but much less so for W), so I will need to think about this more.

## Feb 20, 2019

Am in the midst of testing the main function to see if it produces results at all similar to the 1-year tool. 
## Feb 22, 2019

Spent lots of time tweaking equations and inputs to better align with the tool itself.  THings still needing to do:

1. Redo incidence equations to use Bernoulli format instead of simple multiplication

2. Carry over the changes made in a10_comp_with_excel_gc.R to a10_masterscript.R.  These include adding in the total population (in and out of HS), making the argument passed in for init diagnoses be summer across age and for all diags (in and out of HS).  And others?

3. Add aging! 

## Feb 25, 2019

Redid Bernoulli equations.  Discovered that prev is defined as numbers in one place and prop in another.  Computer issues forcing me to stop.

## Feb 26, 2019

Carried over edits from excel-compare script to master script.
Census data arrived! And added.
Fixed prevalence calculations so they are proportion, not absolute.
Realized aging doesn't really need to happen.
Adjusted pop sizes for cases where enrollment > census

## Mar 8, 2019

As of last week, the code was reproducing the initial diagnoses in the excel comparison model for the output for the first year, but not beyond.I spent some time last Friday (3/1) going through the logic of this in some excel spreadsheets, but then CROI happened.  Picking that back up now. 

It appears I have succeeded! There are tiny effects in the excel-compare model, which appear to be due to (1) an inability to assign ages in the initial diagnoses, which causes the susceptible pool by age to differ slightly in y2 from y1, causing minor deviations even though the tool was calibrated to overall diagnoses; these then magnify with time, but stil lare very slight.

Then I checked out the actual model and it seems to be dong much better.  Need to think about (1) how to deal with sex-specific see-sawing, and (2) should this calibrate in the absence of behavior change?  Or is smoothing the see-sawing enough?

Must add in the race mixing still!

### Keep at bottom

# To do:
- add in race mixing parameters to model
- get race mixing
- test main function
- add in main fxn output
- import diagnoses from every year, not just from 2007? 
      (But the model only uses the first year and then models all the others from there.)
- check if there are any other inputs that need to change by year
